spring:
  application:
    name: web
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: "http://localhost:9090/auth/realms/training"
            user-name-attribute: "preferred_username"
        registration:
          keycloak:
            client-name: "Keycloak"
            client-id: "training-web"
            client-secret: "secret"
            client-authentication-method: "client_secret_post"
            authorizationGrantType: "authorization_code"
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: "openid,profile,email,training"
#server:
#  # to prevent error: Request header is too large
#  max-http-request-header-size: 128KB