### Implicit flow request

GET {{ISSUER}}/protocol/openid-connect/auth?client_id={{PUBLIC_CLIENT_SPA_IMPLICIT}}&redirect_uri={{PUBLIC_CLIENT_SPA_IMPLICIT_REDIRECT}}&state=12345678&response_type=token&scope=openid profile email