
spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: api
          uri: http://localhost:8090
          predicates:
            - Path=/api/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs"
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:9090/auth/realms/training"
        registration:
          keycloak:
            provider: keycloak
            client-id: training-gateway
            client-secret: "secret"
            authorization-grant-type: authorization_code
            scope: openid,training

server.port: 8050

logging.level:
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE
